.TH AXON 1 axon\-VERSION
.SH NAME
axon \- simple terminal
.SH SYNOPSIS
.B axon
[options]
.SH DESCRIPTION
.I axon
is a simple terminal emulator.
.SH OPTIONS
.TP
.B \-v, \-\-version
Display version information and exit.
.TP
.B \-\-color-table
Echo the color codes.
.TP
.BI "\-c, \-\-config " file "
Config file to load instead of default (~/.config/axon/axonrc).
.TP
.BI "\-o, \-\-output " file "
Write the contents of terminal and scrollback to
.I file
on exit.
.TP
.BI "\-d, \-\-working\-directory " dir "
Set initial working directory.
.TP
.BI "\-x, \-\-execute " command "
Execute
.I command
inside the terminal.
.TP
.BI "\-e, \-\-xterm\-execute " program " [ " arguments " ... ] "
Execute
.I program
instead of the shell.  If this is used it must be the 
.B last option
on the command line, as in xterm / rxvt.
.TP
.B \-l, \-\-login
Start terminal shell as a login shell.
.TP
.B \-H, \-\-hold
Prevent window from closing after execute command. This is useful for viewing the output of commands and examining error messages that would otherwise cause the terminal to terminate.
.TP
.BI "\-f, \-\-font " font "
Defines the terminal font to use when axon is run.
.TP
.BI "\-t, \-\-title " title "
Set the inital window title for the terminal (default "axon").
.TP
.B \-s, \-\-fullscreen
Start the terminal in fullscreen mode.
.TP
.B \-m, \-\-maximize
Start the terminal in a maximized state.
.TP
.BI "\-g, \-\-geometry " geometry "
Defines the X11 geometry string, which will fixate the height and width of axon. The form is [=][<width>{xX}<height>][{+-}<xoffset>{+-}<yoffset>]. See
.BR XParseGeometry (3)
for further details.
.TP
.BI "\-\-display " display "
X display to use.
.SH FILES
.I axon
can be customized by creating a custom config.h and (re)compiling the source code. This keeps it fast, secure and simple.
.SH BUGS
See the TODO file in the distribution.
.SH AUTHORS
.B David Luco
<dluco11@gmail.com>
.SH COPYRIGHT
See the LICENSE file for the terms of redistribution.
.SH SEE ALSO
.BR tabbed (1)
