.\" Axon Manpage
.\"
.\" Author: David Luco <dluco11@gmail.com>
.\"
.\" Proccess this file with:
.\" groff -man -Tascii axon.1
.\"
.TH "AXON" "1" "2014-09-10" "axon\-1.0" "User Commands"
.SH NAME
axon \- lightweight terminal emulator
.SH SYNOPSIS
.B axon
[options]
.SH DESCRIPTION
.I axon
is a lightweight vte-based terminal emulator. It aims to be fast, simple, and light on resources.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help options..
.TP
.B \-v, \-\-version
Display version information and exit.
.TP
.B \-\-color-table
Echo the color codes.
.TP
.BI "\-c, \-\-config " file "
Config file to load instead of default (~/.config/axon/axonrc).
.TP
.BI "\-o, \-\-output " file "
Write the contents of terminal and scrollback to
.I file
on exit.
.TP
.BI "\-d, \-\-working\-directory " dir "
Set initial working directory.
.TP
.BI "\-x, \-\-execute " command "
Execute
.I command
inside the terminal.
.TP
.BI "\-e, \-\-xterm\-execute " program " [ " arguments " ... ] "
Execute
.I program
instead of the shell.  If this is used it must be the 
.B last option
on the command line, as in xterm / rxvt.
.TP
.B \-l, \-\-login
Start terminal shell as a login shell.
.TP
.B \-H, \-\-hold
Prevent window from closing after execute command. This is useful for viewing the output of commands and examining error messages that would otherwise cause the terminal to terminate.
.TP
.BI "\-f, \-\-font " font "
Defines the terminal font to use when axon is run.
.TP
.BI "\-t, \-\-title " title "
Set the inital window title for the terminal (default "axon").
.TP
.B \-s, \-\-fullscreen
Start the terminal in fullscreen mode.
.TP
.B \-m, \-\-maximize
Start the terminal in a maximized state.
.TP
.BI "\-g, \-\-geometry " geometry "
Set size and/or position of terminal according to X geometry specification.
.TP
.BI "\-\-display " display "
X display to use.
.SH USAGE
.TP
.B Ctrl\-Shift\-n
Open a new terminal window.
.TP
.B Ctrl\-Shift\-c
Copy selected text.
.TP
.B Ctrl\-Shift\-v
Paste clipboard contents into terminal.
.TP
.B Ctrl\-Shift\-q
Close terminal window.
.TP
.B F11
Toggle fullscreen mode.
.TP
.B Menu
Show context menu (right-click).
.SH FILES
.TP
.I ~/.config/axon/axonrc
Default configuration file.
.SH SEE ALSO
https://github.com/dluco/axon
.SH AUTHOR
.B David Luco
<dluco11@gmail.com>
