.\" Axon Manpage
.\"
.\" Author: David Luco <dluco11@gmail.com>
.\"
.\" Proccess this file with:
.\" groff -man -Tascii axon.1
.\"
.TH "AXON" "1" "2014-09-29" "axon\-3.0.1" "Axon Manual"
.SH NAME
axon \- lightweight terminal emulator
.SH SYNOPSIS
.B axon
[options]
.SH DESCRIPTION
.B axon
is a lightweight vte-based terminal emulator. It aims to be fast, simple, and light on resources.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help options.
.TP
.B \-v, \-\-version
Display version information and exit.
.TP
.BI "\-c, \-\-config " file "
Config file to load instead of default.
.TP
.BI "\-d, \-\-working\-directory " dir "
Set initial working directory.
.TP
.BI "\-x, \-\-command " command "
Execute
.I command
inside the terminal.
.TP
.B \-e, \-execute
Execute the remainder of the arguments inside the terminal.  If this is used it must be the 
.B last option
on the command line, as in xterm / rxvt.
.TP
.B \-l, \-\-login
Start the terminal shell as a login shell.
.TP
.BI "\-t, \-\-title " title "
Set the inital window title for the terminal (default "axon").
.TP
.B \-s, \-\-fullscreen
Start the terminal in fullscreen mode.
.TP
.BI "\-g, \-\-geometry " geometry "
Set the size and/or position of terminal according to X geometry specification.
.TP
.BI "\-\-display " display "
X display to use.
.SH USAGE
.TP
.B Ctrl\-Shift\-n
Open a new terminal window.
.TP
.B Ctrl\-Shift\-c
Copy selected text.
.TP
.B Ctrl\-Shift\-v
Paste clipboard contents into terminal.
.TP
.B Ctrl\-Shift\-r
Reset terminal state and clear scrollback history.
.TP
.B Ctrl\-Shift\-q
Close terminal window.
.TP
.B F11
Toggle fullscreen mode.
.TP
.B Menu
Show context menu (right-click).
.SH FILES
By default
.B axon
will look for a config file first at:
.P
	$XDG_CONFIG_HOME/axon/axonrc
.P
and fallback to:
.P
	$HOME/.axonrc
.P
Reasonable compiled-in default settings will be used if no config file is found. A documented example config file can be found at /usr/share/doc/axon/axonrc.
.SH SEE ALSO
https://github.com/dluco/axon
.SH AUTHOR
.B David Luco
<dluco11@gmail.com>
